### ISSUE TITLE
Geometry(point) not supported

### ISSUE THREAD

**Issue by Diferno** [bbitgmbh/bbit.rdsdata.postgres#1]
Hi!
1st of all, great work and thanks for the efford.

I'm using your wrapper so the migration from postgresql to aurora serverless is as light as it could be tweaking very little of the Sequelize layer, but... I just faced the problem with geometries.

I have a field Point as:
``` 
    locationPoint: {
      type : DataTypes.GEOMETRY('POINT', 4326),
      field: 'location_point'
    },
```
and when saving, I have a sequelize hook that checks if the crs is correctly set, otherwise I set it like: 
``` 
instances.locationPoint.crs = {
          type: 'name',
          properties: {
            name: 'EPSG:4326'
          }
        }
```

The thing is that on save, the data type doesnt seem to be of its please.

```
original: Error: 'posparam5' is an invalid type
      at Function.error (/opt/nodejs/node_modules/@bbitgmbh/bbit.rdsdata.postgres/dist/aws-data-api.js:64:15)
      at Function.formatType (/opt/nodejs/node_modules/@bbitgmbh/bbit.rdsdata.postgres/dist/aws-data-api.js:187:47)
      at Function.formatParam (/opt/nodejs/node_modules/@bbitgmbh/bbit.rdsdata.postgres/dist/aws-data-api.js:102:27)
      at /opt/nodejs/node_modules/@bbitgmbh/bbit.rdsdata.postgres/dist/aws-data-api.js:86:45
      at Array.reduce (<anonymous>)
      at Function.processParams (/opt/nodejs/node_modules/@bbitgmbh/bbit.rdsdata.postgres/dist/aws-data-api.js:75:46)
      at Function.prepareSqlAndParams (/opt/nodejs/node_modules/@bbitgmbh/bbit.rdsdata.postgres/dist/aws-data-api.js:146:60)
      at AwsDataApi.<anonymous> (/opt/nodejs/node_modules/@bbitgmbh/bbit.rdsdata.postgres/dist/aws-data-api.js:319:44)
      at Generator.next (<anonymous>)
      at /opt/nodejs/node_modules/@bbitgmbh/bbit.rdsdata.postgres/dist/aws-data-api.js:27:71 
```

Any help with this??

After digging a little bit more, it appears that the param sent to the insert is a plain object, but if it gets stringifyed, the insertion should work fine, as Sequelize already uses the ST_GeomFromGeoJSON function:
``` 
ST_GeomFromGeoJSON('{"type":"Point","coordinates":[-3.53356,40.4413],"crs":{"type":"name","properties":{"name":"EPSG:4326"}}}')
```

**Comment by Diferno** [comment]
Hi, I just solved it for now doing a JSON.stringify at the beforeSave hook.
